[build]
  command = """
  rustup install nightly --profile minimal \
  && RUSTDOCFLAGS=\"--cfg docsrs\" cargo +nightly doc --no-deps --target-dir=lying-to-netlify
  """
  publish = "lying-to-netlify/docs"

[[redirects]]
  from = "/"
  to = "/tracing"
