[build]
  command = "curl https://sh.rustup.rs -sSf | sh -s -- -y && source $HOME/.cargo/env && RUSTDOCFLAGS=\"--cfg docsrs\" cargo doc --no-deps"
  publish = "target/doc"

[[redirects]]
  from = "/"
  to = "/tracing"
