[build]
  # command = """
  # rustup install nightly --profile minimal \
  # && RUSTDOCFLAGS=\"--cfg docsrs\" cargo +nightly doc --no-deps
  # """
  command = "tree -d /opt/repo"
  publish = "/opt/build/repo/target/docs"

[[redirects]]
  from = "/"
  to = "/tracing"
