[build]
  # command = """
  # rustup install nightly --profile minimal \
  # && RUSTDOCFLAGS=\"--cfg docsrs\" cargo +nightly doc --no-deps
  # """
  publish = "/opt/buildhome/cache/target/docs"

[[redirects]]
  from = "/"
  to = "/tracing"
