[build]
  command = """
  rustup install nightly --profile minimal \
  && RUSTDOCFLAGS=\"--cfg docsrs\" cargo +nightly doc --no-deps
  """
  publish = "target/doc"

[[redirects]]
  from = "/"
  to = "/tracing"
