[package]
name = "tracing-tower"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

[features]
default = ["tower-layer", "tower-util", "http"]

[dependencies]
tracing = "0.1"
tracing-futures = { path = "../tracing-futures" }
futures = "0.1"
tower-service = "0.2"
tower-layer = { version = "0.1", optional = true }
tower-util = { version = "0.1", optional = true }
http = { version = "0.1", optional = true }
