[package]
name = "tracing-macros"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tracing-macros/0.1.0/tracing_macros"
description = """
Macros for emitting trace events
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing"]
license = "MIT"

# [lib]
# proc-macro = true

[features]

[dependencies]
proc-macro-hack = "0.5"
tracing-macro-impls = {version = "0.1", path = "impls"}

[dev-dependencies]
tracing = "0.1"
